<?php
/* 
|---------------------------------------------------
| Creating our global handlers
|---------------------------------------------------
*/



/* 
|---------------------------------------------------
| Creating our country names
|---------------------------------------------------
*/
$ec['country'] = [
    '0' => 'Select Country',
    '1' => 'United States',
    '2' => 'Canada',
    '3' => 'Afghanistan',
    '4' => 'Albania',
    '5' => 'Algeria',
    '6' => 'American Samoa',
    '7' => 'Andorra',
    '8' => 'Angola',
    '9' => 'Anguilla',
    '10' => 'Antarctica',
    '11' => 'Antigua and/or Barbuda',
    '12' => 'Argentina',
    '13' => 'Armenia',
    '14' => 'Aruba',
    '15' => 'Australia',
    '16' => 'Austria',
    '17' => 'Azerbaijan',
    '18' => 'Bahamas',
    '19' => 'Bahrain',
    '20' => 'Bangladesh',
    '21' => 'Barbados',
    '22' => 'Belarus',
    '23' => 'Belgium',
    '24' => 'Belize',
    '25' => 'Benin',
    '26' => 'Bermuda',
    '27' => 'Bhutan',
    '28' => 'Bolivia',
    '29' => 'Bosnia and Herzegovina',
    '30' => 'Botswana',
    '31' => 'Bouvet Island',
    '32' => 'Brazil',
    '34' => 'Brunei Darussalam',
    '35' => 'Bulgaria',
    '36' => 'Burkina Faso',
    '37' => 'Burundi',
    '38' => 'Cambodia',
    '39' => 'Cameroon',
    '40' => 'Cape Verde',
    '41' => 'Cayman Islands',
    '42' => 'Central African Republic',
    '43' => 'Chad',
    '44' => 'Chile',
    '45' => 'China',
    '46' => 'Christmas Island',
    '47' => 'Cocos (Keeling) Islands',
    '48' => 'Colombia',
    '49' => 'Comoros',
    '50' => 'Congo',
    '51' => 'Cook Islands',
    '52' => 'Costa Rica',
    '53' => 'Croatia (Hrvatska)',
    '54' => 'Cuba',
    '55' => 'Cyprus',
    '56' => 'Czech Republic',
    '57' => 'Denmark',
    '58' => 'Djibouti',
    '59' => 'Dominica',
    '60' => 'Dominican Republic',
    '61' => 'East Timor',
    '62' => 'Ecuador',
    '63' => 'Egypt',
    '64' => 'El Salvador',
    '65' => 'Equatorial Guinea',
    '66' => 'Eritrea',
    '67' => 'Estonia',
    '68' => 'Ethiopia',
    '69' => 'Falkland Islands (Malvinas)',
    '70' => 'Faroe Islands',
    '71' => 'Fiji',
    '72' => 'Finland',
    '73' => 'France',
    '74' => 'France, Metropolitan',
    '75' => 'French Guiana',
    '76' => 'French Polynesia',
    '77' => 'French Southern Territories',
    '78' => 'Gabon',
    '79' => 'Gambia',
    '80' => 'Georgia',
    '81' => 'Germany',
    '82' => 'Ghana',
    '83' => 'Gibraltar',
    '84' => 'Greece',
    '85' => 'Greenland',
    '86' => 'Grenada',
    '87' => 'Guadeloupe',
    '88' => 'Guam',
    '89' => 'Guatemala',
    '90' => 'Guinea',
    '91' => 'Guinea-Bissau',
    '92' => 'Guyana',
    '93' => 'Haiti',
    '94' => 'Heard and Mc Donald Islands',
    '95' => 'Honduras',
    '96' => 'Hong Kong',
    '97' => 'Hungary',
    '98' => 'Iceland',
    '99' => 'India',
    '100' => 'Indonesia',
    '101' => 'Iran (Islamic Republic of)',
    '102' => 'Iraq',
    '103' => 'Ireland',
    '104' => 'Israel',
    '105' => 'Italy',
    '106' => 'Ivory Coast',
    '107' => 'Jamaica',
    '108' => 'Japan',
    '109' => 'Jordan',
    '110' => 'Kazakhstan',
    '111' => 'Kenya',
    '112' => 'Kiribati',
    '113' => 'Korea, Democratic People\'s Republic of',
    '114' => 'Korea, Republic of',
    '115' => 'Kosovo',
    '116' => 'Kuwait',
    '117' => 'Kyrgyzstan',
    '118' => 'Lao People\'s Democratic Republic',
    '119' => 'Latvia',
    '120' => 'Lebanon',
    '121' => 'Lesotho',
    '122' => 'Liberia',
    '123' => 'Libyan Arab Jamahiriya',
    '124' => 'Liechtenstein',
    '125' => 'Lithuania',
    '126' => 'Luxembourg',
    '127' => 'Macau',
    '128' => 'Macedonia',
    '129' => 'Madagascar',
    '130' => 'Malawi',
    '131' => 'Malaysia',
    '132' => 'Maldives',
    '133' => 'Mali',
    '134' => 'Malta',
    '135' => 'Marshall Islands',
    '136' => 'Martinique',
    '137' => 'Mauritania',
    '138' => 'Mauritius',
    '139' => 'Mayotte',
    '140' => 'Mexico',
    '141' => 'Micronesia, Federated States of',
    '142' => 'Moldova, Republic of',
    '143' => 'Monaco',
    '144' => 'Mongolia',
    '145' => 'Montenegro',
    '146' => 'Montserrat',
    '147' => 'Morocco',
    '148' => 'Mozambique',
    '149' => 'Myanmar',
    '150' => 'Namibia',
    '151' => 'Nauru',
    '152' => 'Nepal',
    '153' => 'Netherlands',
    '154' => 'Netherlands Antilles',
    '155' => 'New Caledonia',
    '156' => 'New Zealand',
    '157' => 'Nicaragua',
    '158' => 'Niger',
    '159' => 'Nigeria',
    '160' => 'Niue',
    '161' => 'Norfork Island',
    '162' => 'Northern Mariana Islands',
    '163' => 'Norway',
    '164' => 'Oman',
    '165' => 'Pakistan',
    '166' => 'Palau',
    '167' => 'Panama',
    '168' => 'Papua New Guinea',
    '169' => 'Paraguay',
    '170' => 'Peru',
    '171' => 'Philippines',
    '172' => 'Pitcairn',
    '173' => 'Poland',
    '174' => 'Portugal',
    '175' => 'Puerto Rico',
    '176' => 'Qatar',
    '177' => 'Reunion',
    '178' => 'Romania',
    '179' => 'Russian Federation',
    '180' => 'Rwanda',
    '181' => 'Saint Kitts and Nevis',
    '182' => 'Saint Lucia',
    '183' => 'Saint Vincent and the Grenadines',
    '184' => 'Samoa',
    '185' => 'San Marino',
    '186' => 'Sao Tome and Principe',
    '187' => 'Saudi Arabia',
    '188' => 'Senegal',
    '189' => 'Serbia',
    '190' => 'Seychelles',
    '191' => 'Sierra Leone',
    '192' => 'Singapore',
    '193' => 'Slovakia',
    '194' => 'Slovenia',
    '195' => 'Solomon Islands',
    '196' => 'Somalia',
    '197' => 'South Africa',
    '198' => 'South Georgia South Sandwich Islands',
    '199' => 'Spain',
    '200' => 'Sri Lanka',
    '201' => 'St. Helena',
    '202' => 'St. Pierre and Miquelon',
    '203' => 'Sudan',
    '204' => 'Suriname',
    '205' => 'Svalbarn and Jan Mayen Islands',
    '206' => 'Swaziland',
    '207' => 'Sweden',
    '208' => 'Switzerland',
    '209' => 'Syrian Arab Republic',
    '210' => 'Taiwan',
    '211' => 'Tajikistan',
    '212' => 'Tanzania, United Republic of',
    '213' => 'Thailand',
    '214' => 'Togo',
    '215' => 'Tokelau',
    '216' => 'Tonga',
    '217' => 'Trinidad and Tobago',
    '218' => 'Tunisia',
    '219' => 'Turkey',
    '220' => 'Turkmenistan',
    '221' => 'Turks and Caicos Islands',
    '222' => 'Tuvalu',
    '223' => 'Uganda',
    '224' => 'Ukraine',
    '225' => 'United Arab Emirates',
    '226' => 'United Kingdom',
    '227' => 'United States minor outlying islands',
    '228' => 'Uruguay',
    '229' => 'Uzbekistan',
    '230' => 'Vanuatu',
    '231' => 'Vatican City State',
    '232' => 'Venezuela',
    '233' => 'Vietnam',
    '238' => 'Yemen',
    '239' => 'Yugoslavia',
    '240' => 'Zaire',
    '241' => 'Zambia',
    '242' => 'Zimbabwe'
];

/* 
|---------------------------------------------------
| Functions for Getting country names
|---------------------------------------------------
*/


/* 
|---------------------------------------------------
| Creating our country names
|---------------------------------------------------
*/

$ec['branch'] = [
    '0' => 'Select Branch',
    '1' => 'United Kingdom',
    '2' => 'Turkey',
    '3' => 'Spain',
    '4' => 'Nigeria',
    '5' => 'Brazil',
    '6' => 'Ghana'
];

/* 
|---------------------------------------------------
| Functions for Getting branch name
|---------------------------------------------------
*/



/* 
|---------------------------------------------------
| Handler for months
|---------------------------------------------------
*/

$ec['months'] = [
    '1' => 'January',
    '2' => 'February',
    '3' => 'March',
    '4' => 'April',
    '5' => 'May',
    '6' => 'June',
    '7' => 'July',
    '8' => 'August',
    '9' => 'September',
    '10' => 'October',
    '11' => 'November',
    '12' => 'December'
];

/* 
|---------------------------------------------------
| Supported TimeZone
|---------------------------------------------------
*/

$ec['timezone'] = [
    '0' => 'UTC',
    '1' => 'Africa/Abidjan',
    '2' => 'Africa/Accra',
    '3' => 'Africa/Addis_Ababa',
    '4' => 'Africa/Algiers',
    '5' => 'Africa/Asmara',
    '6' => 'Africa/Cairo',
    '7' => 'Africa/Casablanca',
    '8' => 'Africa/Johannesburg',
    '9' => 'Africa/Lagos',
    '10' => 'Africa/Nairobi',
    '11' => 'Africa/Tripoli',
    '12' => 'America/Argentina/Catamarca',
    '13' => 'America/Aruba',
    '14' => 'America/Barbados',
    '15' => 'America/Belize',
    '16' => 'America/Chicago',
    '17' => 'America/Costa_Rica',
    '18' => 'America/Indiana/Knox',
    '19' => 'America/Jamaica',
    '20' => 'America/Los_Angeles',
    '21' => 'America/Mexico_City',
    '22' => 'America/Monterrey',
    '23' => 'America/New_York',
    '24' => 'America/Sao_Paulo',
    '25' => 'America/Toronto',
    '26' => 'Antarctica/Casey',
    '27' => 'Antarctica/Davis',
    '28' => 'Antarctica/Macquarie',
    '29' => 'Antarctica/Palmer',
    '30' => 'Arctic/Longyearbyen',
    '31' => 'Asia/Baku',
    '32' => 'Asia/Dacca',
    '34' => 'Asia/Hong_Kong',
    '35' => 'Asia/Istanbul',
    '36' => 'Asia/Dhaka',
    '37' => 'Asia/Jerusalem',
    '38' => 'Asia/Kolkata',
    '39' => 'Asia/Kuwait',
    '40' => 'Asia/Seoul',
    '41' => 'Asia/Tokyo',
    '42' => 'Asia/Qatar',
    '43' => 'Asia/Shanghai',
    '44' => 'Atlantic/Azores',
    '45' => 'Atlantic/Bermuda',
    '46' => 'Atlantic/Bermuda',
    '47' => 'Atlantic/Cape_Verde',
    '48' => 'Atlantic/South_Georgia',
    '49' => 'Atlantic/Stanley',
    '50' => 'Atlantic/St_Helena',
    '51' => 'Australia/ACT',
    '52' => 'Australia/Brisbane',
    '53' => 'Australia/Lindeman',
    '54' => 'Australia/Queensland',
    '55' => 'Australia/South',
    '56' => 'Europe/Amsterdam',
    '57' => 'Europe/Andorra',
    '58' => 'Europe/Berlin',
    '59' => 'Europe/Dublin',
    '60' => 'Europe/Istanbul',
    '61' => 'Europe/Lisbon',
    '62' => 'Europe/Madrid',
    '63' => 'Europe/Luxembourg',
    '64' => 'Europe/Paris',
    '65' => 'Europe/San_Marino',
    '66' => 'Europe/Rome',
    '67' => 'Europe/Monaco',
    '68' => 'Europe/Moscow',
    '69' => 'Indian/Antananarivo',
    '70' => 'Indian/Cocos',
    '71' => 'Indian/Mauritius',
    '72' => 'Indian/Comoro',
    '73' => 'Indian/Mayotte',
    '74' => 'Indian/Chagos',
    '75' => 'Indian/Reunion',
    '76' => 'Pacific/Apia',
    '77' => 'Pacific/Fiji',
    '78' => 'Pacific/Johnston',
    '79' => 'Pacific/Kiritimati',
    '80' => 'Pacific/Midway',
    '81' => 'Pacific/Marquesas'
];

/* 
|---------------------------------------------------
| Function for Getting timezone name
|---------------------------------------------------
*/



/* 
|---------------------------------------------------
| IDs for database table validation
|---------------------------------------------------
*/

$ec['id'] = [
    '1' => 1,
    '2' => 2,
    '3' => 3,
    '4' => 4,
    '5' => 5,
    '6' => 6,
    '7' => 7,
    '8' => 8,
    '9' => 9,
    '10' => 10,
    '11' => 11,
    '12' => 12,
    '13' => 13,
    '14' => 14,
    '15' => 15,
];